import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Blog Page",
  description: "Generated by create next app",
};
const BlogLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <h1>Blog layout</h1>
      <div className="flex justify-between">
        {children}
        <div className="w-1/3">Sidebar</div>
      </div>
    </div>
  );
};

export default BlogLayout;
